bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

lawforyou/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import handler404    

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('appointment/', include('appointment.urls')),
    path('services/', include('services.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('forecast/', include('forecast.urls')),
    path('faq/', include('faq.urls')),
]

handler404 = 'lawforyou.views.handler404'
handler403 = 'lawforyou.views.handler403'
handler500 = 'lawforyou.views.handler500'

services/urls.py
from django.urls import path, include
from .views import ServiceTemplateView
from . import views

urlpatterns = [
    path("", ServiceTemplateView.as_view(), name="services"),
    path('add/', views.add_product, name='add_product'),
    path('<slug:url>/', views.product_detail, name='product_detail'),
    path('edit/<slug:url>/', views.edit_product, name='edit_product'),
    path('delete/<slug:url>/', views.delete_product, name='delete_product'),
    path('<slug:url>/edit_review/<int:review_id>',
         views.review_edit, name='review_edit'),
    path('<slug:url>/delete_review/<int:review_id>',
         views.review_delete, name='review_delete'),
]

services/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator


RATINGS = ((None, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'))

# Create your models here.


class Product(models.Model):
    """
    The model indicates the products
    """
    item = models.IntegerField(null=True)
    name = models.CharField(max_length=254)
    url = models.SlugField(max_length=300, null=True, unique=True)
    image = models.ImageField(null=True, blank=True)
    description = models.TextField(
        validators=[
            MinLengthValidator(1)
            ]
        )
    summary = models.TextField(blank=True)
    cooperation_partner = models.CharField(default='Svedea', max_length=100)
    has_cooperation_partner = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        ordering = ['item']

    def __str__(self):
        return self.name


class Review(models.Model):
    """
    The model indicates the reviews for products
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name="reviews")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=500)
    rating = models.IntegerField(choices=RATINGS, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.comment} - by {self.user}"

services/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Review


class ProductForm(forms.ModelForm):

    url = forms.SlugField(max_length=300)
    url.widget = forms.TextInput(
        attrs={'pattern': "^[a-z0-9_]+(?:-[a-z0-9_]+)*$",
               'title': "Please Enter Valid URL (No space)"})
    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput)

    class Meta:
        model = Product
        fields = '__all__'


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('comment', 'rating')

services/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.views import generic
from .models import Product, Review
from django.contrib.auth.decorators import login_required
from .forms import ProductForm, ReviewForm

# Create your views here.


class ServiceTemplateView(generic.ListView):
    template_name = 'services/services.html'
    queryset = Product.objects.all()

    paginate_by = 6


def product_detail(request, url):
    """ Display detailed product """
    queryset = Product.objects.all()
    product = get_object_or_404(queryset, url=url)
    reviews = product.reviews.all().order_by("-created_at")
    if request.method == "POST":
        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.product = product
            review.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Review submitted')
        else:
            messages.error(request,
                           ('Failed to add review. '
                            'Ensure the form is valid and '
                            'you added a rating'))

    review_form = ReviewForm()

    return render(
        request,
        "services/product_detail.html",
        {"product": product,
            "reviews": reviews,
            "review_form": review_form, },
    )


def review_edit(request, url, review_id):
    """
    view to edit reviews
    """
    if request.method == "POST":

        queryset = Product.objects.all()
        product = get_object_or_404(queryset, url=url)
        review = get_object_or_404(Review, pk=review_id)
        review_form = ReviewForm(data=request.POST, instance=review)

        if review_form.is_valid() and review.user == request.user:
            review = review_form.save(commit=False)
            review.product = product
            review.save()
            messages.add_message(request, messages.SUCCESS, 'Review Updated!')
        else:
            messages.add_message(request, messages.ERROR, 'Failed to update, make sure you put also rating!')  # noqa

    return redirect(reverse('product_detail', args=[url]))


def review_delete(request, url, review_id):
    """
    view to delete review
    """
    queryset = Product.objects.all()
    product = get_object_or_404(queryset, url=url)
    review = get_object_or_404(Review, pk=review_id)

    if review.user == request.user:
        review.delete()
        messages.add_message(request, messages.SUCCESS, 'Review deleted!')
    else:
        messages.add_message(request, messages.ERROR, 'Error delete!')

    return redirect(reverse('product_detail', args=[url]))


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.url]))
        else:
            messages.error(request,
                           ('Failed to add product. '
                            'Please ensure the form is valid.'))
    else:
        form = ProductForm()

    template = 'services/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, url):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, url=url)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.url]))
        else:
            messages.error(request,
                           ('Failed to update product. '
                            'Please ensure the form is valid.'))
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'services/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, url):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, url=url)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('services'))

services/templates/services/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'services' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

services/templates/services/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Edit a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'edit_product' product.url %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'services' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Update Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

services/templates/services/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block content %}
<section class="container-fluid">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
      <div class="image-container my-5">
        {% if product.image %}
        <a href="{{ product.image.url }}" target="_blank">
          <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
        </a>
        {% else %}
        <a href="">
          <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
        </a>
        {% endif %}
        <hr>
        <p class="text-center"> <em>Please don't forget to leave a review below as well. We appreciate your feedback!</em></p>
      </div>
      {% if product.has_cooperation_partner %}
        <p class="cooperate-partner text-center text-secondary text-uppercase" style="font-family: 'Crimson Text';"> In cooperation with:
          {{ product.cooperation_partner}}
        </p>
        {% endif %}
    </div>
    <div class="col-12 col-md-6 col-lg-4">
      <div class="product-details-container mb-5 mt-md-5">
        <h2>{{ product.name }}</h2>
        <h3 class="lead mb-0 text-left"> ${{ product.price }}</h3>
        {% if request.user.is_superuser %}
        <small>
          <a href="{% url 'edit_product' product.url %}">Edit</a> |
          <a class="text-danger" href="{% url 'delete_product' product.url %}">Delete</a>
        </small>
        {% endif %}
        <p class="mt-3">{{ product.description }}</p>
        <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
          {% csrf_token %}
          <div class="form-row">

            <div class="col-12">
              <p class="mt-3"><strong>Quantity:</strong></p>
              <div class="form-group w-50">
                <div class="input-group input-group-{{ product.id }}">
                  <div class="input-group-prepend">
                    <button class="decrement-qty btn btn-black rounded-0 decrement-qty_{{ product.id }}" 
                                                data-item_id="{{ product.id }}">
                      <span class="icon">
                        <i class="fas fa-minus"></i>
                      </span>
                    </button>
                  </div>
                  <input class="form-control qty_input id_qty_{{ product.id }}" type="number" name="quantity" value="1" min="1" max="99"
                  data-item_id="{{ product.id }}">
                  <div class="input-group-append">
                    <button class="increment-qty btn btn-black rounded-0 increment-qty_{{ product.id }}"
                                                data-item_id="{{ product.id }}">
                      <span class="icon">
                        <i class="fas fa-plus"></i>
                      </span>
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div class="col{% if s %}-12 mt-2{% endif %}">
              <a href="{% url 'services' %}" class="btn btn-outline-black rounded-0 mt-5">
                <span class="icon">
                  <i class="fas fa-chevron-left"></i>
                </span>
                <span class="text-uppercase">Keep Shopping</span>
              </a>
              <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
            </div>
            <input type="hidden" name="redirect_url" value="{{ request.path }}">

          </div>
        </form>
      </div>
    </div>
  </div>

  <hr>
  <!-- Review area -->
  <div class="row">
    <div class="col-md-8 card mb-4 mt-3">

      <div class="card-body">
        <h3 class="">Reviews: </h3>
        {% for review in reviews %}
        <div class="p-2 reviews border mt-2" style="background-color: #f5eeee;">
          <p class="font-weight-bold"> <i class="far fa-user"></i>
            {{ review.user}}
            <span>
              <i class="rating-star fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}"
                aria-hidden="true" style="float: right;"></i>
              <i class="rating-star fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}"
                aria-hidden="true" style="float: right;"></i>
              <i class="rating-star fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}"
                aria-hidden="true" style="float: right;"></i>
              <i class="rating-star fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}"
                aria-hidden="true" style="float: right;"></i>
              <i class="rating-star fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}"
                aria-hidden="true" style="float: right;"></i>
            </span>
            <span class="font-weight-normal p-2"><i class="far fa-clock"></i>
              {{ review.created_at }}
            </span>
          </p>
          <div id="review{{ review.id }}">
            {{ review.comment | linebreaks }}
          </div>
          {% if user.is_authenticated and review.user == user %}
          <button class="btn btn-edit" data-review_id="{{ review.id }}">Edit</button>
          <button class="btn btn-delete" data-review_id="{{ review.id }}">Delete</button>
          {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>
    <!-- Field for adding comments  -->
    <div class="col-md-4 card mb-4 mt-3">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h3>Write your review:</h3>
        <p>Posting as: {{ user.username }}</p>
        <form id="reviewForm" method="post" class='rating-form' name="reviewForm">
          {{ review_form | crispy }}
          {% csrf_token %}
          <span class="rating">
            <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
            <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
            <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
            <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
            <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
            <input type="radio" name="rating" value="-1" checked>
          </span>
          <button id="submitButton" type="submit" class="btn btn-primary btn-lg">Submit</button>
        </form>
        {% else %}
        <p>Log in to leave a review</p>
        {% endif %}
      </div>
    </div>
  </div>
</section>



<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete review?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your review?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block postloadjs %}
<script src="{% static 'js/reviews.js' %}"></script>
{{ block.super }}

{% include 'services/includes/quantity_input_script.html' %}
{% endblock %}

services/templates/services/services.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="container services-page">
  <div class="row">
    <div class="col card mb-4 mt-3 left top">
      <div class="card-body full-post-text">
        <div class="service-summary text-center">
          <h1 class="text-uppercase"> <strong>Our service </strong></h1>
          <br>
          <div class="card-header text-center uppercase border"> <strong class="text-white text-uppercase"> We recommend</strong></div>
        </div>
        <hr>

        <div class="row">
          <!-- Product Entries Column -->
          <div id="posts" class="col-12 mt-3 left">
            <div class="row">
              {% for service in product_list %}
              <div class="col-md-4">
                <div class="card mb-4 text-center">
                  <div class="card-body w-100 h-100 card-lawforyou border">
                    <div class="image-container">
                      {% if service.image %}
                      <img class="card-img-top" src="{{ service.image.url }}" alt="{{ service.name }}">
                      {% else%}
                      <img class="card-img-top" src="{{ MEDIA_URL }}noimage.webp" alt="{{ service.name }}">
                      {% endif %}
                    </div>
                    <br>
                    <h2 class="card-title">{{ service.name }}</h2>
                    <hr>
                    <p class="card-text"> <em> {{ service.summary }} </em></p>
                    <p class="card-text"><strong class="border border-secondary pl-1 pr-1 bg-warning"> Price: ${{ service.price }} </strong></p>
                    <a href="{{ service.url }}" class="btn btn-primary">Buy Now</a>
                  </div>
                </div>
              </div>
              {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">

              {% endif %}
              {% endfor %}

            </div>
          </div>
        </div>

        {% if is_paginated %}
        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
              <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; Previous</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> Next &raquo;</a></li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}

      </div>
    </div>
  </div>
</section>

    {% endblock content %}
    {% block extras %}
    {% endblock %}